### ISSUE TITLE
_nds folder is hidden

### ISSUE THREAD

**Issue by mentionmenot** [MechanicalDragon0687/NDSForwarder#13]
I always put my NDS ROM files inside _nds folder to reduce folder number in sd card root and to easier file management, since _nds folder is hidden I cannot install NDS game like 1.0.0 version because I cannot get in that to hit "Install All" button. I don't see any benefits of hiding that folder so could you please bring it back?

**Comment by MechanicalDragon0687** [comment]
The _nds folder is considered a system folder. It was hidden to prevent issues with people putting their roms into it, then trying to load them later with any other app that uses the _nds folder. 
I understand the desire to reduce folder count on the sd for organization, but that would be like saving your documents to the Windows or /sys/ folder because you didnt want to clog your Documents folder.

I have no plans to bring this back as it was never intended in the first place. An extra folder doesnt add much clutter, and you can still hide it within some other folder if absolutely desired. For example, all of my game copies are within their own system's folder in /roms:
/roms/nds
/roms/gba
/roms/nes
etc

this means /roms is the only extra folder on sd root for me in regards to ALL of my systems
